export const projects = [
	{
		id: 6,
		title: 'Montagne',
		date: 'Juillet 2022',
		languages: ['Sass', 'HTML5'],
		infos: 'Site vitrine. Premier vrai projet codé en Sass',
		img: '/assets/img/projet-1.jpg',
		link: 'https://thibaultg94.github.io/Projet_1/',
	},
	{
		id: 5,
		title: 'Le Resto',
		date: 'Août 2022',
		languages: ['Sass', 'HTML5'],
		infos: 'Deuxième gros projet de site vitrine codé en Sass',
		img: '/assets/img/projet-2.jpg',
		link: 'https://thibaultg94.github.io/Projet_2/',
	},
	{
		id: 3,
		title: 'Helium',
		date: 'Septembre 2022',
		languages: ['Sass', 'HTML5', 'JavaScript'],
		infos: "Copie du site Helium. La barre de navigation et quelques lancements d'animation ont été codés en JavaScript",
		img: '/assets/img/projet-3.jpg',
		link: 'https://thibaultg94.github.io/Projet_3/',
	},
	{
		id: 2,
		title: 'Bubble Game',
		date: 'Aout 2022',
		languages: ['JavaScript', 'CSS', 'HTML5'],
		infos: 'Petit jeu rigolo codé avec JavaScript. Il faut cliquer sur les bulles sans en manquer pour gagner !',
		img: '/assets/img/projet-4.jpg',
		link: 'https://thibaultg94.github.io/Projet_4/',
	},
	{
		id: 1,
		title: 'API Countries',
		date: 'Septembre 2022',
		languages: ['JavaScript', 'CSS', 'HTML5'],
		infos: 'API recensant les pays du monde. On peut faire une recherche pour trouver un pays, trier les pays par population ou par ordre alphabétique',
		img: '/assets/img/projet-5.jpg',
		link: 'https://thibaultg94.github.io/Projet_5/',
	},
	{
		id: 4,
		title: 'Password Generator',
		date: 'Septembre 2022',
		languages: ['CSS', 'HTML5', 'JavaScript'],
		infos: 'Générateur de mot de passes',
		img: '/assets/img/projet-6.jpg',
		link: 'https://thibaultg94.github.io/Projet_6/',
	},
	{
		id: 7,
		title: 'ToDo List',
		date: 'Septembre 2022',
		languages: ['CSS', 'JavaScript', 'HTML5'],
		infos: 'ToDo List',
		img: '/assets/img/projet-7.jpg',
		link: 'https://thibaultg94.github.io/Projet_7/',
	},
];
