export const projects = [
	{
		id: 1,
		title: 'Yoga App',
		date: 'Octobre 2022',
		languages: ['CSS', 'JavaScript', 'HTML5'],
		infos: 'Application exercices pour faire une routine Yoga',
		img: '/assets/img/projet-10.jpg',
		link: 'https://thibaultg94.github.io/Projet_10/',
		github: 'https://github.com/ThibaultG94/Yoga-routine_POO',
	},
	{
		id: 2,
		title: 'API Countries',
		date: 'Septembre 2022',
		languages: ['JavaScript', 'CSS', 'HTML5'],
		infos: 'API recensant les pays du monde. On peut faire une recherche pour trouver un pays, trier les pays par population ou par ordre alphabétique',
		img: '/assets/img/projet-5.jpg',
		link: 'https://thibaultg94.github.io/Projet_5/',
		github: 'https://github.com/ThibaultG94/-TP9--Country-App',
	},
	{
		id: 3,
		title: 'Helium',
		date: 'Septembre 2022',
		languages: ['Sass', 'HTML5', 'JavaScript'],
		infos: "Copie du site Helium. La barre de navigation et quelques lancements d'animation ont été codés en JavaScript",
		img: '/assets/img/projet-3.jpg',
		link: 'https://thibaultg94.github.io/Projet_3/',
		github: 'https://github.com/ThibaultG94/Projet_3-Integration_Helium',
	},
	{
		id: 4,
		title: 'Bubble Game',
		date: 'Aout 2022',
		languages: ['JavaScript', 'CSS', 'HTML5'],
		infos: 'Petit jeu rigolo codé avec JavaScript. Il faut cliquer sur les bulles sans en manquer pour gagner !',
		img: '/assets/img/projet-4.jpg',
		link: 'https://thibaultg94.github.io/Projet_4/',
		github: 'https://github.com/ThibaultG94/Projet_2-Generateur_de_bulle',
	},
	{
		id: 5,
		title: 'Date Calculator',
		date: 'Septembre 2022',
		languages: ['Sass', 'JavaScript', 'HTML5'],
		infos: 'Calcule les dates',
		img: '/assets/img/projet-8.jpg',
		link: 'https://thibaultg94.github.io/Projet_8/',
		github: 'https://github.com/ThibaultG94/TP8--Date_Calculator',
	},
	{
		id: 6,
		title: 'Portfolio Bootstrap',
		date: 'Octobre 2022',
		languages: ['Bootstrap', 'Sass', 'HTML5'],
		infos: 'Porfolio John Doe codé en Bootstrap',
		img: '/assets/img/projet-11.jpg',
		link: 'https://thibaultg94.github.io/Projet_11/',
		github: 'https://github.com/ThibaultG94/Projet-Bootstrap_5',
	},
	{
		id: 7,
		title: 'Password Generator',
		date: 'Septembre 2022',
		languages: ['CSS', 'HTML5', 'JavaScript'],
		infos: 'Générateur de mot de passes',
		img: '/assets/img/projet-6.jpg',
		link: 'https://thibaultg94.github.io/Projet_6/',
		github: 'https://github.com/ThibaultG94/Generateur_de_mot_de_passe',
	},
	{
		id: 8,
		title: 'Le Resto',
		date: 'Août 2022',
		languages: ['Sass', 'HTML5'],
		infos: 'Deuxième gros projet de site vitrine codé en Sass',
		img: '/assets/img/projet-2.jpg',
		link: 'https://thibaultg94.github.io/Projet_2/',
		github: 'https://github.com/ThibaultG94/Projet_2-Integration_Le_Resto',
	},
	{
		id: 9,
		title: 'Joke App',
		date: 'Septembre 2022',
		languages: ['CSS', 'JavaScript', 'HTML5'],
		infos: 'Api Joke',
		img: '/assets/img/projet-9.jpg',
		link: 'https://thibaultg94.github.io/Projet_9/',
		github: 'https://github.com/ThibaultG94/joke-app',
	},
	{
		id: 10,
		title: 'Montagne',
		date: 'Juillet 2022',
		languages: ['Sass', 'HTML5'],
		infos: 'Site vitrine. Premier vrai projet codé en Sass',
		img: '/assets/img/projet-1.jpg',
		link: 'https://thibaultg94.github.io/Projet_1/',
		github: 'https://github.com/ThibaultG94/Projet_1-Int-gration_La_Montagne',
	},
	{
		id: 11,
		title: 'ToDo List',
		date: 'Septembre 2022',
		languages: ['CSS', 'JavaScript', 'HTML5'],
		infos: 'ToDo List',
		img: '/assets/img/projet-7.jpg',
		link: 'https://thibaultg94.github.io/Projet_7/',
		github: 'https://github.com/ThibaultG94/TP6---Todo-List',
	},
];
