export const projects = [
	{
		id: 1,
		title: 'Yoga App',
		date: 'Octobre 2022',
		languages: [
			'../assets/img/css.png',
			'../assets/img/js.png',
			'../assets/img/html.png',
		],
		infos: "Application pour créer une routine d'exercices Yoga. Codé en POO avec JavaScript",
		img: '/assets/img/projet-10.jpg',
		link: 'https://thibaultg94.github.io/Projet_10/',
		github: 'https://github.com/ThibaultG94/Yoga-routine_POO',
	},
	{
		id: 2,
		title: 'Forum Firebase',
		date: 'Décembre 2022',
		languages: [
			'../assets/img/react-redux.png',
			'../assets/img/firebase.png',
			'../assets/img/sass.png',
		],
		infos: 'Petit forum codé en React avec Redux pour la gestion du store. Le back est assuré par Firebase',
		img: '/assets/img/projet-firebase-redux.jpg',
		link: 'https://react-firebase-forum.vercel.app/',
		github: 'https://github.com/ThibaultG94/react-firebase',
	},
	{
		id: 3,
		title: 'Vitrine Helium',
		date: 'Septembre 2022',
		languages: [
			'../assets/img/sass.png',
			'../assets/img/html.png',
			'../assets/img/js.png',
		],
		infos: "Copie du site vitrine Helium. Les lancements d'animations ont été codés avec JavaScript",
		img: '/assets/img/projet-3.jpg',
		link: 'https://thibaultg94.github.io/Projet_3/',
		github: 'https://github.com/ThibaultG94/Projet_3-Integration_Helium',
	},
	{
		id: 4,
		title: 'Vitrine Le Resto',
		date: 'Août 2022',
		languages: ['../assets/img/sass.png', '../assets/img/html.png'],
		infos: 'Deuxième site vitrine codé avec Sass',
		img: '/assets/img/projet-2.jpg',
		link: 'https://thibaultg94.github.io/Projet_2/',
		github: 'https://github.com/ThibaultG94/Projet_2-Integration_Le_Resto',
	},
	{
		id: 5,
		title: 'Portfolio Bootstrap',
		date: 'Octobre 2022',
		languages: [
			'../assets/img/bootstrap.png',
			'../assets/img/sass.png',
			'../assets/img/html.png',
		],
		infos: 'Porfolio John Doe codé en Bootstrap',
		img: '/assets/img/projet-11.jpg',
		link: 'https://thibaultg94.github.io/Projet_11/',
		github: 'https://github.com/ThibaultG94/Projet-Bootstrap_5',
	},
	{
		id: 6,
		title: 'Vitrine Montagne',
		date: 'Juillet 2022',
		languages: ['../assets/img/sass.png', '../assets/img/html.png'],
		infos: 'Premier site vitrine codé avec Sass',
		img: '/assets/img/projet-1.jpg',
		link: 'https://thibaultg94.github.io/Projet_1/',
		github: 'https://github.com/ThibaultG94/Projet_1-Int-gration_La_Montagne',
	},
	{
		id: 7,
		title: 'API Countries',
		date: 'Octobre 2022',
		languages: [
			'../assets/img/react.png',
			'../assets/img/sass.png',
			'../assets/img/html.png',
		],
		infos: 'API recensant les pays du monde. On peut faire une recherche pour trouver un pays, trier les pays par population ou par ordre alphabétique',
		img: '/assets/img/projet-react-1.jpg',
		link: 'https://first-react-app-murex.vercel.app/',
		github: 'https://github.com/ThibaultG94/projet-react-1',
	},
	{
		id: 8,
		title: 'React Cooking App',
		date: 'Novembre 2022',
		languages: [
			'../assets/img/react.png',
			'../assets/img/sass.png',
			'../assets/img/html.png',
		],
		infos: 'API pour chercher des recettes de cuisine',
		img: '/assets/img/projet-react-2.jpg',
		link: 'https://react-cooking-app.vercel.app/',
		github: 'https://github.com/ThibaultG94/React-TP1--Cooking_App',
	},
	{
		id: 9,
		title: 'Date Calculator',
		date: 'Septembre 2022',
		languages: [
			'../assets/img/sass.png',
			'../assets/img/js.png',
			'../assets/img/html.png',
		],
		infos: 'Formulaire pour sélectionner les dates de vacances et calculer le prix total',
		img: '/assets/img/projet-8.jpg',
		link: 'https://thibaultg94.github.io/Projet_8/',
		github: 'https://github.com/ThibaultG94/TP8--Date_Calculator',
	},
	{
		id: 10,
		title: 'Bubble Game',
		date: 'Aout 2022',
		languages: [
			'../assets/img/js.png',
			'../assets/img/css.png',
			'../assets/img/html.png',
		],
		infos: 'Petit jeu sympathique codé avec JavaScript. Il faut cliquer sur le plus de bulles possibles !',
		img: '/assets/img/projet-4.jpg',
		link: 'https://thibaultg94.github.io/Projet_4/',
		github: 'https://github.com/ThibaultG94/Projet_2-Generateur_de_bulle',
	},
	{
		id: 11,
		title: 'Password Generator',
		date: 'Septembre 2022',
		languages: [
			'../assets/img/css.png',
			'../assets/img/html.png',
			'../assets/img/js.png',
		],
		infos: "Application pour générer un mot de passe selon les critères choisis par l'utilisateur",
		img: '/assets/img/projet-6.jpg',
		link: 'https://thibaultg94.github.io/Projet_6/',
		github: 'https://github.com/ThibaultG94/Generateur_de_mot_de_passe',
	},
	{
		id: 12,
		title: 'Joke App',
		date: 'Septembre 2022',
		languages: [
			'../assets/img/css.png',
			'../assets/img/js.png',
			'../assets/img/html.png',
		],
		infos: "Petite application qui génère une nouvelle blague à chaque fois qu'on clique dessus. L'application utilise l'api de blablagues.net",
		img: '/assets/img/projet-9.jpg',
		link: 'https://thibaultg94.github.io/Projet_9/',
		github: 'https://github.com/ThibaultG94/joke-app',
	},
	{
		id: 13,
		title: 'ToDo List',
		date: 'Septembre 2022',
		languages: [
			'../assets/img/css.png',
			'../assets/img/js.png',
			'../assets/img/html.png',
		],
		infos: 'Petite application "ToDo List" pour créer, valider et supprimer des tâches. Celles-ci sont sauvegardées dans le localStorage',
		img: '/assets/img/projet-7.jpg',
		link: 'https://thibaultg94.github.io/Projet_7/',
		github: 'https://github.com/ThibaultG94/TP6---Todo-List',
	},
];
